### cơ chế  reset pasword
### b1 điền vào ô mail để lấy lại mật khẩu hoặc vào chế độ quên mật khẩu của hệ thống
### b2 vào đường link confim code niếu thành công api này sẻ gửi về một mã token (mã tokent có hiệu lực trong một tiếng)
### b3 vào đường link nhập mật khẩu mới sau khi nhập mật khẩu mới thì đồng thười trả về một token đăng nhập

### cơ chế  đăng ký
### b1 khi đăng ký kể cả form điền mật khẩu mới api sẽ trả một token
### b2 vào đường link confim code


### sig
###     login       bắt buộc không có Authorization trong header
POST  http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email":"leehaau@gmail.com",
    "password":"123456"
}
### OUPUT
{
  "status": 200,
  "message": "login done",
  "data": {
    "role": "admin",
    "token": " eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAzOTk5MTgsImV4cCI6MTY5Mjk5MTkxOH0.2sA_tczYKgqKcXA4RPU2Ttdo1nIz2yvp1EviOKiw8Cc"
  }
}
###     register    bắt buộc không có Authorization trong header
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
    "firstName":"hau",
    "lastName":"leung",
    "email": "letrunghu@gmail.com",
    "password":"gggg",
    "gender":"nam"
}
### OUPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzFhNzk4OGIwYzUzYmQ5ZmYiLCJkVHlwZSI6IiQyYiQxMCRlOUdqYVJpNlBZdU9XcEtEbnVzR0plQWZlMXZzVTBaVzhyUWxoaVlQR3hycG9mWVJ6dzdrQyIsImlhdCI6MTY5MDQwMDA3MCwiZXhwIjoxNjkwNDAzNjcwfQ.Ov8wJTXEjekZePi94Fe7Y55wS2fh4-IzLpxeFrzUHnM"
  }
}
###     email verification  Authorization teken riêng dùng để xác thực mà register trả về trước đó
POST http://localhost:8080/api/v1/register-verification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDZiZGRmNDAyZjgyOThjMGUiLCJkVHlwZSI6IiQyYiQxMCQwQVdldTczYWZHVktmS2NySi8xeHJ1SlZVL0VWQ0NTN0g5RUpMdFdwQlJWbENleVptVVM1cSIsImlhdCI6MTY5MDM5ODg0MCwiZXhwIjoxNjkwNDAyNDQwfQ.Pn7h8IfkmZ6SK7UhYokQsGqyCLjXq2zn6WdCjEkkwxg

{
    "verificationCode":"590649"
} 
### OUTPUT
{
  "status": 200,
  "message": "done",
  "data": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDZiZGRmNDAyZjgyOThjMGUiLCJpYXQiOjE2OTA0MDAxMDMsImV4cCI6MTY5Mjk5MjEwM30.XSNbIcnIeQeVScKgcZJ8tAgaAcW6yfytVzp6UmvjEUg"
}
###     reset-password trong trường người dùng còn đăng nhập nên lấy luôn token
GET http://localhost:8080/api/v1/reset-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDZiZGRmNDAyZjgyOThjMGUiLCJkVHlwZSI6IiQyYiQxMCQwQVdldTczYWZHVktmS2NySi8xeHJ1SlZVL0VWQ0NTN0g5RUpMdFdwQlJWbENleVptVVM1cSIsImlhdCI6MTY5MDM5ODg0MCwiZXhwIjoxNjkwNDAyNDQwfQ.Pn7h8IfkmZ6SK7UhYokQsGqyCLjXq2zn6WdCjEkkwxg
###OUPUT
{
  "status": 200,
  "message": "done",
  "data": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDZiZGRmNDAyZjgyOThjMGUiLCJpYXQiOjE2OTA0MDAxMDMsImV4cCI6MTY5Mjk5MjEwM30.XSNbIcnIeQeVScKgcZJ8tAgaAcW6yfytVzp6UmvjEUg"
}
###     reset-password trong trường người không còn đăng nhập nên nhập mail để gửi thông tin
POST  http://localhost:8080/api/v1/reset-password
Content-Type: application/json

{
    "email":"letrunghau@gmail.com"
}
###OUPUT
{
  "status": 200,
  "message": "done",
  "data": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDZiZGRmNDAyZjgyOThjMGUiLCJpYXQiOjE2OTA0MDAxMDMsImV4cCI6MTY5Mjk5MjEwM30.XSNbIcnIeQeVScKgcZJ8tAgaAcW6yfytVzp6UmvjEUg"
}
###     reset-password-verification xác thực mail để lấy mật khẩu mới
POST  http://localhost:8080/api/v1/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDZiZGRmNDAyZjgyOThjMGUiLCJkVHlwZSI6IiQyYiQxMCQwQVdldTczYWZHVktmS2NySi8xeHJ1SlZVL0VWQ0NTN0g5RUpMdFdwQlJWbENleVptVVM1cSIsImlhdCI6MTY5MDM5ODg0MCwiZXhwIjoxNjkwNDAyNDQwfQ.Pn7h8IfkmZ6SK7UhYokQsGqyCLjXq2zn6WdCjEkkwxg

{
    "verificationCode":"590649"
}
###OUPUT
{
  "status": 200,
  "message": "done",
  "data": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDZiZGRmNDAyZjgyOThjMGUiLCJpYXQiOjE2OTA0MDAxMDMsImV4cCI6MTY5Mjk5MjEwM30.XSNbIcnIeQeVScKgcZJ8tAgaAcW6yfytVzp6UmvjEUg"
}
###     new pasword sau khi xác thwucj thành công thì chuyển trang đến trang nhập mật khẩu mới
POST  http://localhost:8080/api/v1/new-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDZiZGRmNDAyZjgyOThjMGUiLCJkVHlwZSI6IiQyYiQxMCQwQVdldTczYWZHVktmS2NySi8xeHJ1SlZVL0VWQ0NTN0g5RUpMdFdwQlJWbENleVptVVM1cSIsImlhdCI6MTY5MDM5ODg0MCwiZXhwIjoxNjkwNDAyNDQwfQ.Pn7h8IfkmZ6SK7UhYokQsGqyCLjXq2zn6WdCjEkkwxg

{
    "pasword":"590649"
} 
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDZiZGRmNDAyZjgyOThjMGUiLCJpYXQiOjE2OTA0MDAxMDMsImV4cCI6MTY5Mjk5MjEwM30.XSNbIcnIeQeVScKgcZJ8tAgaAcW6yfytVzp6UmvjEUg"
}






### account
###     change Password                                             tùy thuộc vào user nào mà đổi mật khẩu của user đó
PUT  http://localhost:8080/api/v1/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "oldPassword":"hau123",
    "newPassword":"123456"
}
###OUTPUT
{
  "status": 200,
  "message": "update done"
}
###     password status                                             tùy thuộc vào user nào mà đổi mật khẩu của user đó
GET http://localhost:8080/api/v1/password-status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "modifiedAt": "2023-07-23T17:09:22.000Z"
  }
}


###     password status By email
GET http://localhost:8080/api/v1/password-status/leehaau@gmail.com
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "modifiedAt": "2023-07-23T17:09:22.000Z"
  }
}









### address ------------------------------------------------------------------------------------------
###     getAddress | get address main in user id
GET http://localhost:8080/api/v1/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "userId": "43fec0ef558c1ad0bb",
    "district": "tên huyện",
    "commune": "tên xã",
    "phone": "123456789",
    "province": "Đồng Tháp",
    "status": "main",
    "detail": "số nhà số đường",
    "addressId": "53834bfdbb5978cb71",
    "user_id": "43fec0ef558c1ad0bb"
  }
}
###     getListAddress | get list address in user id
GET http://localhost:8080/api/v1/addresses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "userId": "43fec0ef558c1ad0bb",
      "district": "nnnn",
      "commune": "hnhjhh",
      "phone": "0123456789",
      "province": "hhh",
      "status": "main",
      "detail": "jjjj",
      "addressId": "6e812dd35bc4bdd02f",
      "user_id": "43fec0ef558c1ad0bb"
    },
    {
      "userId": "43fec0ef558c1ad0bb",
      "district": "GHZmmmjjbbb",
      "commune": "bc A",
      "phone": "1234587014",
      "province": "Đồng Tháp",
      "status": "main",
      "detail": "số xxx",
      "addressId": "dd2000f516ac03d4f9",
      "user_id": "43fec0ef558c1ad0bb"
    }
  ]
}
###     addAddress      
POST  http://localhost:8080/api/v1/address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "province":"Đồng Tháp",
    "district": "GHZmmmjjbbb",
    "commune":"bc A",
    "detail":"số xxx",
    "phone": "1234587014",
    "status":"main"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "province": "Đồng Tháp",
    "district": "GHZmmmjjbbb",
    "commune": "bc A",
    "detail": "số xxx",
    "phone": "1234587014",
    "status": "main",
    "userId": "43fec0ef558c1ad0bb",
    "addressId": "dd2000f516ac03d4f9"
  }
}

###     editAddress
PUT  http://localhost:8080/api/v1/address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "addressId":"6e812dd35bc4bdd02f",
    "province":"hhh",
    "district": "nnnn",
    "commune":"hnhjhh",
    "detail":"jjjj",
    "phone": "0123456789",
    "status":"main"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "userId": "43fec0ef558c1ad0bb",
    "district": "nnnn",
    "commune": "hnhjhh",
    "phone": "0123456789",
    "province": "hhh",
    "status": "main",
    "detail": "jjjj",
    "addressId": "6e812dd35bc4bdd02f",
    "user_id": "43fec0ef558c1ad0bb"
  }
}
###     deleteAddress
DELETE  http://localhost:8080/api/v1/address/53834bfdbb5978cb71
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done"
}





### bill ------------------------------------------------------------------------------------------
###     getListBill
###     getListBillByUserId
###     getBillByOrderId






### blog ------------------------------------------------------------------------------------------
###     getBlog
GET http://localhost:8080/api/v1/blog/1251d74f5b5bf1485e
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "blogId": "1251d74f5b5bf1485e",
    "blogCategoryId": "af20a79d5cf8dec0ed",
    "userId": null,
    "title": "Tiêu đề cua bài viết a",
    "thumbnail": "this is data",
    "introduction": "hello các bạn trẻ",
    "content": "txt",
    "createdAt": "2023-07-17T21:09:59.000Z",
    "modifiedAt": "2023-07-26T19:58:02.000Z",
    "views": 5,
    "user_id": null,
    "blog_category_id": "af20a79d5cf8dec0ed"
  }
}
###     getAllBlog
GET http://localhost:8080/api/v1/blogs
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "blogId": "1251d74f5b5bf1485e",
      "blogCategoryId": "af20a79d5cf8dec0ed",
      "userId": null,
      "title": "Tiêu đề cua bài viết a",
      "thumbnail": "this is data",
      "introduction": "hello các bạn trẻ",
      "content": "txt",
      "createdAt": "2023-07-17T21:09:59.000Z",
      "modifiedAt": "2023-07-26T19:58:02.000Z",
      "views": 6,
      "user_id": null,
      "blog_category_id": "af20a79d5cf8dec0ed"
    },
    {
      "blogId": "7e65a3cd5dca21c8db",
      "blogCategoryId": "af20a79d5cf8dec0ed",
      "userId": null,
      "title": "Tiêu đề cua bài viết b",
      "thumbnail": "data txt abcc",
      "introduction": "hello các bạn trẻ",
      "content": "txt",
      "createdAt": "2023-07-23T06:25:08.000Z",
      "modifiedAt": "2023-07-23T06:25:08.000Z",
      "views": 0,
      "user_id": null,
      "blog_category_id": "af20a79d5cf8dec0ed"
    }
  ]
}
###     getListBlogBycategoryId
###     addBlog admin role
POST  http://localhost:8080/api/v1/blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "blogCategoryId":"af20a79d5cf8dec0ed",
    "title":"bài viết của ai đó",
    "thumbnail":"dozzzzz",
    "introduction":"hello các bạn trẻ",
    "content":"sssssabc"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "blogCategoryId": "af20a79d5cf8dec0ed",
    "title": "bài viết của ai đó",
    "thumbnail": "dozzzzz",
    "introduction": "hello các bạn trẻ",
    "content": "sssssabc",
    "userId": "43fec0ef558c1ad0bb",
    "blogId": "860bdf7be56e2f313a",
    "createdAt": "2023-07-26T20:03:21.159Z",
    "modifiedAt": "2023-07-26T20:03:21.159Z",
    "views": 0
  }
}
###     editBlog admin role
PUT  http://localhost:8080/api/v1/blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "blogId": "860bdf7be56e2f313a",
    "blogCategoryId":"af20a79d5cf8dec0ed",
    "title":"hola ha lo ",
    "thumbnail":"ví fuj thumbneil",
    "introduction":"hello các bạn trẻ",
    "content":"ggggg"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "blogId": "860bdf7be56e2f313a",
    "blogCategoryId": "af20a79d5cf8dec0ed",
    "userId": "43fec0ef558c1ad0bb",
    "title": "hola ha lo ",
    "thumbnail": "ví fuj thumbneil",
    "introduction": "hello các bạn trẻ",
    "content": "ggggg",
    "createdAt": "2023-07-26T20:03:21.000Z",
    "modifiedAt": "2023-07-26T20:07:17.000Z",
    "views": 0,
    "user_id": "43fec0ef558c1ad0bb",
    "blog_category_id": "af20a79d5cf8dec0ed"
  }
}
###     deleteBlog admin role
DELETE  http://localhost:8080/api/v1/blog/860bdf7be56e2f313a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

###OUTPUT
{
  "status": 200,
  "message": "done"
}








### Blog Categories ------------------------------------------------------------------------------------------
###     get
GET http://localhost:8080/api/v1/blog-category/3dfbbbd9cfa514442d
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "blogCategoryId": "3dfbbbd9cfa514442d",
    "name": "blog vui chơi",
    "parent": "abcgf"
  }
}
###     getAll
GET http://localhost:8080/api/v1/blog-categories
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "blogCategoryId": "3dfbbbd9cfa514442d",
      "name": "blog vui chơi",
      "parent": "abcgf"
    },
    {
      "blogCategoryId": "af20a79d5cf8dec0ed",
      "name": "blog giả thuật",
      "parent": "kgggjhghjgjhg"
    }
  ]
}
###     add
POST  http://localhost:8080/api/v1/blog-category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "name":"blog giải trí",
    "parent":"abcgf"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "name": "blog giải trí",
    "parent": "abcgf",
    "blogCategoryId": "c423c5399c2f371576"
  }
}
###     edit
PUT   http://localhost:8080/api/v1/blog-category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "blogCategoryId": "af20a79d5cf8dec0ed",
    "name":"blog giả thuật",  
    "parent":"kgggjhghjgjhg"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "blogCategoryId": "af20a79d5cf8dec0ed",
    "name": "blog giả thuật",
    "parent": "kgggjhghjgjhg"
  }
}
###     delete
DELETE    http://localhost:8080/api/v1/blog-category/af20a79d5cf8dec0ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

###OUTPUT
{
  "status": 200,
  "message": "done"
}





### brand ------------------------------------------------------------------------------------------
###     get one
GET http://localhost:8080/api/v1/brand/c0f56594fa0a87a3c8
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "brandId": "c0f56594fa0a87a3c8",
    "name": "dien tu mobi",
    "description": "sdfsdzf",
    "blogLink": "dsfxcvzfd"
  }
}

###     getAll
GET http://localhost:8080/api/v1/brands
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "brandId": "c0f56594fa0a87a3c8",
      "name": "dien tu mobi",
      "description": "sdfsdzf",
      "blogLink": "dsfxcvzfd"
    },
    {
      "brandId": "d454e763e9aacb559f",
      "name": "nhãn hàng a",
      "description": "chuyên cũng cấp mặt hàng b",
      "blogLink": "dsfxcvzfd"
    }
  ]
}

###     add
POST http://localhost:8080/api/v1/brand
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
      "name": "nhãn hàng a",
      "description": "chuyên cũng cấp mặt hàng b",
      "blogLink": "dsfxcvzfd"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "name": "nhãn hàng a",
    "description": "chuyên cũng cấp mặt hàng b",
    "blogLink": "dsfxcvzfd",
    "brandId": "d454e763e9aacb559f"
  }
}

###     edit
PUT  http://localhost:8080/api/v1/brand
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "brandId": "c0f56594fa0a87a3c8",
      "name": "dien tu mobi",
      "description": "linh kiện giá tốt",
      "blogLink": "dsfxcvzfd"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "brandId": "c0f56594fa0a87a3c8",
    "name": "dien tu mobi",
    "description": "linh kiện giá tốt",
    "blogLink": "dsfxcvzfd"
  }
}
###     delete 
DELETE  http://localhost:8080/api/v1/brand/c0f56594fa0a87a3c8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

###OUTPUT
{
  "status": 200,
  "message": "done"
}





### cart ------------------------------------------------------------------------------------------
###     get cart
GET http://localhost:8080/api/v1/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "cartId": "422b9bc8085ef90823",
      "quantity": 40,
      "Product": {
        "productId": "10e32bc189f5959a39",
        "name": "dasas",
        "price": 79843,
        "information": "hjgfhj"
      }
    },
    {
      "cartId": "d2cc77814bc6b279c8",
      "quantity": 3,
      "Product": {
        "productId": "1e48622b6f61216f82",
        "name": "dasas",
        "price": 79843,
        "information": "hjgfhj"
      }
    }
  ]
}
###     add to cart
POST   http://localhost:8080/api/v1/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
  "productId":"1e48622b6f61216f82"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "cartId": "d2cc77814bc6b279c8",
    "quantity": 3,
    "Product": {
      "productId": "1e48622b6f61216f82",
      "name": "dasas",
      "price": 79843,
      "information": "hjgfhj"
    }
  }
}

###     edit value product in cart
PUT    http://localhost:8080/api/v1/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
  "cartId":"422b9bc8085ef90823",
  "quantity":2
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "cartId": "422b9bc8085ef90823",
    "quantity": 40,
    "Product": {
      "productId": "10e32bc189f5959a39",
      "name": "dasas",
      "price": 79843,
      "information": "hjgfhj"
    }
  }
}
###     delete product in cart 
DELETE    http://localhost:8080/api/v1/cart/f7798ff2d38d826a75
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done"
}







### categories ------------------------------------------------------------------------------------------
###     get
GET  http://localhost:8080/api/v1/category/1335921e1ce62b7d65
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "name": "máy hàn",
    "parent": null,
    "image": "jhgjhghghjgjhg",
    "categoryId": "1335921e1ce62b7d65"
  }
}
###     getAll
GET  http://localhost:8080/api/v1/categories
###OUTPUT

{
  "status": 200,
  "message": "done",
  "data": [
    {
      "name": "máy hàn",
      "parent": "null",
      "image": "jhgjhghghjgjhg",
      "categoryId": "1335921e1ce62b7d65"
    },
    {
      "name": "máy hàn 997",
      "parent": "categoryId",
      "image": "jhgjhghghjgjhg",
      "categoryId": "4c582c4eda0544bf6a"
    }
  ]
}
###     add   admin role
POST   http://localhost:8080/api/v1/category
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "name": "máy hàn45",
    "parent": "caoriry id",
    "image":"jhgjhghghjgjhg"

}
### OTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "name": "máy hàn45",
    "parent": "caoriry id",
    "image": "jhgjhghghjgjhg",
    "categoryId": "4c582c4eda0544bf6a"
  }
}
###     edit  admin role
PUT http://localhost:8080/api/v1/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "categoryId": "4c582c4eda0544bf6a",
    "name": "máy hàn 997",
    "parent": "categoryId",
    "image":"jhgjhghghjgjhg"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "name": "máy hàn 997",
    "parent": "categoryId",
    "image": "jhgjhghghjgjhg",
    "categoryId": "4c582c4eda0544bf6a"
  }
}
###     delete    admin role
DELETE http://localhost:8080/api/v1/category/4c582c4eda0544bf6a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

###OUPUT
{
  "status": 200,
  "message": "done"
}





### discount ------------------------------------------------------------------------------------------
###     get     
GET http://localhost:8080/api/v1/discount/8ef0c57e2305c805ea
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "discountId": "8ef0c57e2305c805ea",
    "createdAt": "2023-07-17T21:25:46.000Z",
    "modifiedAt": "2023-07-23T06:42:57.000Z",
    "enableAt": "2023-07-17T21:09:59.000Z",
    "disableAt": "2026-07-17T21:09:59.000Z",
    "type": "cc",
    "value": 176.8645,
    "quantity": 15,
    "code": "nhap code"
  }
}

###     getAll  admin role
GET http://localhost:8080/api/v1/discounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "discountId": "8ef0c57e2305c805ea",
      "createdAt": "2023-07-17T21:25:46.000Z",
      "modifiedAt": "2023-07-23T06:42:57.000Z",
      "enableAt": "2023-07-17T21:09:59.000Z",
      "disableAt": "2026-07-17T21:09:59.000Z",
      "type": "cc",
      "value": 176.8645,
      "quantity": 15,
      "code": "nhap code"
    },
    {
      "discountId": "9284fc741e51391bc6",
      "createdAt": "2023-07-23T06:43:22.000Z",
      "modifiedAt": "2023-07-23T06:43:23.000Z",
      "enableAt": "2023-07-17T21:09:59.000Z",
      "disableAt": "2024-07-17T21:09:59.000Z",
      "type": "cc",
      "value": 50,
      "quantity": 15,
      "code": "nhap code"
    }
  ]
}
###     add  | Trường type tương lai sẽ chỉ cho nhập 2 giá trị: 'percent' hoặc 'value'
POST  http://localhost:8080/api/v1/discount
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5YWM5NWNjNjgxOTk5ZWQ1NWEiLCJyb2xlIjoidXNlciIsImlhdCI6MTY4OTAyMDQwNiwiZXhwIjoxNjkxNjEyNDA2fQ.VnPyBNl5q6S9hQMXucrZv_mcNaab4g4bY2myHr3-KTU

{
    "enableAt":"2023-07-17T21:09:59.000Z",
    "disableAt":"2024-07-17T21:09:59.000Z",
    "type":"phantrawm",
    "value":50.000,
    "quantity":15,
    "code":"nhap code"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "enableAt": "2023-07-17T21:09:59.000Z",
    "disableAt": "2024-07-17T21:09:59.000Z",
    "type": "phantrawm",
    "value": 50,
    "quantity": 15,
    "code": "nhap code",
    "discountId": "9fe7f614cbbacc2959",
    "createdAt": "2023-07-27T19:59:36.528Z",
    "modifiedAt": "2023-07-27T19:59:36.528Z"
  }
}
###     edit
PUT  http://localhost:8080/api/v1/discount
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5YWM5NWNjNjgxOTk5ZWQ1NWEiLCJyb2xlIjoidXNlciIsImlhdCI6MTY4OTAyMDQwNiwiZXhwIjoxNjkxNjEyNDA2fQ.VnPyBNl5q6S9hQMXucrZv_mcNaab4g4bY2myHr3-KTU

{
    "discountId": "9fe7f614cbbacc2959",
    "enableAt":"2023-07-17T21:09:59.000Z",
    "disableAt":"2026-07-17T21:09:59.000Z",
    "type":"cc",
    "value":200.8645,
    "quantity":10,
    "code":"nhap code"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "discountId": "9fe7f614cbbacc2959",
    "createdAt": "2023-07-27T19:59:36.000Z",
    "modifiedAt": "2023-07-27T20:00:22.000Z",
    "enableAt": "2023-07-17T21:09:59.000Z",
    "disableAt": "2026-07-17T21:09:59.000Z",
    "type": "cc",
    "value": 200.8645,
    "quantity": 10,
    "code": "nhap code"
  }
}
###     delete  
DELETE http://localhost:8080/api/v1/discount/8ef0c57e2305c805ea
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done"
}


### distributor ------------------------------------------------------------------------------------------
###     getAll
###     add
###     edit
###     delete  
### importduct ------------------------------------------------------------------------------------------
###     getAll
###     add
###     edit
###     delete 




### notification ------------------------------------------------------------------------------------------
###     get trả về thông báo mà hiện tại đang có hiệu lực
GET  http://localhost:8080/api/v1/current-notifications
###     get
GET  http://localhost:8080/api/v1/notification/94ff7147ca4c9f7c4b
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "notificationId": "94ff7147ca4c9f7c4b",
    "name": "hello",
    "enableAt": "2023-07-17T09:30:54.000Z",
    "disableAt": "2023-08-17T09:30:54.000Z",
    "userId": "43fec0ef558c1ad0bb",
    "content": "motoj hangf daif lee thee",
    "user_id": "43fec0ef558c1ad0bb"
  }
}
###     getAll
GET  http://localhost:8080/api/v1/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "notificationId": "3b732ea9de1a4bb84e",
      "name": "hello",
      "enableAt": "2023-07-17T09:30:54.000Z",
      "disableAt": "2023-08-17T09:30:54.000Z",
      "userId": null,
      "content": "motoj hangf daif lee thee",
      "user_id": null
    },
    {
      "notificationId": "7aba53c611627dbf27",
      "name": "hhhh",
      "enableAt": "2023-07-17T09:30:54.000Z",
      "disableAt": "2023-08-17T09:30:54.000Z",
      "userId": null,
      "content": "một ngày dài lê thê",
      "user_id": null
    }
  ]
}
###     add
POST  http://localhost:8080/api/v1/notification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "name":"hello",
    "enableAt":"2023-07-17T09:30:54.000Z",
    "disableAt":"2023-08-17T09:30:54.000Z",
    "content":"motoj hangf daif lee thee"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "name": "hello",
    "enableAt": "2023-07-17T09:30:54.000Z",
    "disableAt": "2023-08-17T09:30:54.000Z",
    "content": "motoj hangf daif lee thee",
    "userId": "43fec0ef558c1ad0bb",
    "notificationId": "e61601a8fe65dbd096"
  }
}
###     edit
PUT   http://localhost:8080/api/v1/notification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "notificationId": "2f752cae91a9f8a1f8",
    "name":"ghtz",
    "enableAt":"2023-07-17T09:30:54.000Z",
    "disableAt":"2023-08-17T09:30:54.000Z",
    "content":"một ngày dài lê thê"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "notificationId": "2f752cae91a9f8a1f8",
    "name": "ghtz",
    "enableAt": "2023-07-17T09:30:54.000Z",
    "disableAt": "2023-08-17T09:30:54.000Z",
    "userId": "43fec0ef558c1ad0bb",
    "content": "một ngày dài lê thê",
    "user_id": "43fec0ef558c1ad0bb"
  }
}
###     delete
DELETE    http://localhost:8080/api/v1/notification/2f752cae91a9f8a1f8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done"
}




### order ------------------------------------------------------------------------------------------
###note: progress có các trạng thái: chờ được sử lý, đơn hàng được chấp nhận, đang sử lý, đang giao, giao thành công | khi đơn hàng đã chấp nhận thì người dùng không được xóa,đơn hàng đang giao thì không thay đổi được địa chỉ, khi đơn hàng giao thành công thì tự động sinh ra bill
###     checkout
POST      http://localhost:8080/api/v1/order/checkout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
  "addressId": "6e812dd35bc4bdd02f",
  "discountCode":"abc"
}

###     get all

###     get by status | user role | lấy danh sách đơn hàng theo từng điều kiện | wait, accept, handle, delivery, done, cancel
GET     http://localhost:8080/api/v1/orders/wait

###     edit | user role | người dùng đổi thông tin giao hàng trước khi giao hàng
PUT     http://localhost:8080/api/v1/order/2f752cae91a9f8a1f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
  "addressId":"ddd"
}


###     delete | user role | người dùng hủy đơn hàng trước khi đơn hàng chấp nhận | đổi thông tin thành cancel chứ không xóa đơn hàng đi 
DELETE    http://localhost:8080/api/v1/order/2f752cae91a9f8a1f8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A


###     edit | admin role | thay đổi trạng thái đơn hàng
PUT     http://localhost:8080/api/v1/admin/order/2f752cae91a9f8a1f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
  "status":"ddd"
}
###     get all | admin role | lấy danh sách đơn hàng để sử lý
GET     http://localhost:8080/api/v1/admin/orders
###     get all | admin role | lấy danh sách đơn hàng để sử lý
GET     http://localhost:8080/api/v1/admin/orders





### product ------------------------------------------------------------------------------------------
###     get
GET http://localhost:8080/api/v1/product/1e48622b6f61216f82
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "productId": "1e48622b6f61216f82",
    "name": "dasas",
    "categoryId": "1335921e1ce62b7d65",
    "quantity": 9,
    "brandId": "c0f56594fa0a87a3c8",
    "information": "hjgfhj",
    "price": 79843,
    "status": "disable",
    "createdAt": "2023-07-17T09:20:10.000Z",
    "modifiedAt": "2023-07-17T09:20:10.000Z",
    "brand_id": "c0f56594fa0a87a3c8",
    "category_id": "1335921e1ce62b7d65"
  }
}
###     getAll
GET http://localhost:8080/api/v1/products
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "productId": "10e32bc189f5959a39",
      "name": "dasas",
      "categoryId": "1335921e1ce62b7d65",
      "quantity": 9,
      "brandId": null,
      "information": "hjgfhj",
      "price": 79843,
      "status": "disable",
      "createdAt": "2023-07-17T09:30:54.000Z",
      "modifiedAt": "2023-07-17T09:30:54.000Z",
      "brand_id": null,
      "category_id": "1335921e1ce62b7d65"
    },
    {
      "productId": "1e48622b6f61216f82",
      "name": "dasas",
      "categoryId": "1335921e1ce62b7d65",
      "quantity": 9,
      "brandId": "c0f56594fa0a87a3c8",
      "information": "hjgfhj",
      "price": 79843,
      "status": "disable",
      "createdAt": "2023-07-17T09:20:10.000Z",
      "modifiedAt": "2023-07-17T09:20:10.000Z",
      "brand_id": "c0f56594fa0a87a3c8",
      "category_id": "1335921e1ce62b7d65"
    }
  ]
}
###     add |admin role | không có trường quantity, trường này phải vào import product mà thêm
POST  http://localhost:8080/api/v1/product
Content-Type: application/json

{
    "name": "dasas",
    "categoryId": "1335921e1ce62b7d65",
    "brandId": null,
    "information": "hjgfhj",
    "price": 79843,
    "status": "disable"
}
###OUPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "name": "dasas",
    "categoryId": "1335921e1ce62b7d65",
    "quantity": 0,
    "brandId": null,
    "information": "hjgfhj",
    "price": 79843,
    "status": "disable",
    "productId": "975e1e6aee63ed996a",
    "createdAt": "2023-07-27T20:03:41.896Z",
    "modifiedAt": "2023-07-27T20:03:41.896Z"
  }
}
###     edit
PUT  http://localhost:8080/api/v1/product
Content-Type: application/json 

{
    "productId": "26da307e352dc63dd2",
      "name": "jhg",
      "categoryId": "1335921e1ce62b7d65",
      "brandId": "c0f56594fa0a87a3c8",
      "information": "sssss",
      "price": 79843,
      "status": "enable",
      "brandId": "c0f56594fa0a87a3c8",
      "categoryId": "1335921e1ce62b7d65"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "productId": "26da307e352dc63dd2",
    "name": "jhg",
    "categoryId": "1335921e1ce62b7d65",
    "quantity": 0,
    "brandId": "c0f56594fa0a87a3c8",
    "information": "sssss",
    "price": 79843,
    "status": "enable",
    "createdAt": "2023-07-27T20:08:24.000Z",
    "modifiedAt": "2023-07-27T20:09:32.000Z",
    "brand_id": "c0f56594fa0a87a3c8",
    "category_id": "1335921e1ce62b7d65"
  }
}
###     delete
DELETE http://localhost:8080/api/v1/product/26da307e352dc63dd2

###OUTPUT
{
  "status": 200,
  "message": "done"
}




### product detail ------------------------------------------------------------------------------------------
###     get
GET http://localhost:8080/api/v1/product-detail/fc04640964cfb8f125
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "productDetailId": "fc04640964cfb8f125",
    "specifications": "hello",
    "productId": null,
    "description": "đây là sản phẩm không bán",
    "content": "my content",
    "location": "my location",
    "product_id": null
  }
}
###     get all | admin role | 
GET http://localhost:8080/api/v1/products-detail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "productDetailId": "fc04640964cfb8f125",
      "specifications": "hello",
      "productId": null,
      "description": "đây là sản phẩm không bán",
      "content": "my content",
      "location": "my location",
      "product_id": null
    },
    {
      "productDetailId": "fcfd7859c15dea8494",
      "specifications": "hello",
      "productId": null,
      "description": "đây là sản phẩm không bán",
      "content": "my content",
      "location": "my location",
      "product_id": null
    }
  ]
}
###     get by product id 
GET http://localhost:8080/api/v1/product-detail-product-id/10e32bc189f5959a39
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "productDetailId": "fcfd7859c15dea8494",
    "specifications": "abc",
    "productId": "10e32bc189f5959a39",
    "description": "đây là sản phẩm không bán",
    "content": "my content",
    "location": "my location",
    "product_id": "10e32bc189f5959a39"
  }
}

###     add | admin role | product not null, this exemple is test 
POST  http://localhost:8080/api/v1/product-detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "specifications":"hello",
    "productId":null,
    "description":"đây là sản phẩm không bán",
    "content":"my content",
    "location":"my location"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "specifications": "hello",
    "productId": null,
    "description": "đây là sản phẩm không bán",
    "content": "my content",
    "location": "my location",
    "productDetailId": "25d087b21eac2b6bef"
  }
}
###     edit | admin role | product not null, this exemple is test 
PUT  http://localhost:8080/api/v1/product-detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "productDetailId":"fcfd7859c15dea8494",
    "specifications":"abc",
    "productId":"10e32bc189f5959a39",
    "description":"đây là sản phẩm không bán",
    "content":"my content",
    "location":"my location"
}
###OUPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "productDetailId": "25d087b21eac2b6bef",
    "specifications": "abc",
    "productId": "10e32bc189f5959a39",
    "description": "đây là sản phẩm không bán",
    "content": "my content",
    "location": "my location",
    "product_id": "10e32bc189f5959a39"
  }
}
###     delete
DELETE  http://localhost:8080/api/v1/product-detail/25d087b21eac2b6bef
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

###OUTPUT
{
  "status": 200,
  "message": "done"
}




### product image ------------------------------------------------------------------------------------------
###     get | lấy hình ảnh dự theo id
GET http://localhost:8080/api/v1/product-image/71ecec94d98f92a37e
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "productImageId": "71ecec94d98f92a37e",
    "productId": "10e32bc189f5959a39",
    "name": "value test",
    "main": true,
    "image": "f88",
    "product_id": "10e32bc189f5959a39"
  }
}
###     get | lấy hình ảnh chính dự theo product id
GET http://localhost:8080/api/v1/product-image-main-product-id/10e32bc189f5959a39
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "productImageId": "71ecec94d98f92a37e",
    "productId": "10e32bc189f5959a39",
    "name": "value test",
    "main": true,
    "image": "f88",
    "product_id": "10e32bc189f5959a39"
  }
}
###     get | lấy nhiều hình ảnh dựa trên product id (ưu tiên dùng api này rồi sử lý về sau hạn chế gọi nhiều lần api)
GET http://localhost:8080/api/v1/product-images-product-id/10e32bc189f5959a39
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "productImageId": "71ecec94d98f92a37e",
      "productId": "10e32bc189f5959a39",
      "name": "value test",
      "main": true,
      "image": "f88",
      "product_id": "10e32bc189f5959a39"
    },
    {
      "productImageId": "9a2de5307920108882",
      "productId": "10e32bc189f5959a39",
      "name": "value test 456",
      "main": true,
      "image": "f88",
      "product_id": "10e32bc189f5959a39"
    }
  ]
}
###     get | admin role | lấy tất cả hình ảnh
GET http://localhost:8080/api/v1/product-images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "productImageId": "71ecec94d98f92a37e",
      "productId": "10e32bc189f5959a39",
      "name": "value test",
      "main": true,
      "image": "f88",
      "product_id": "10e32bc189f5959a39"
    },
    {
      "productImageId": "9a2de5307920108882",
      "productId": "10e32bc189f5959a39",
      "name": "value test 456",
      "main": true,
      "image": "f88",
      "product_id": "10e32bc189f5959a39"
    }
  ]
}
###     add | admin role | tạo hình ảnh
POST  http://localhost:8080/api/v1/product-image
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "productId":"10e32bc189f5959a39",
    "name":"value test",
    "main":true,
    "image":"f88"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "productId": "10e32bc189f5959a39",
    "name": "value test",
    "main": true,
    "image": "f88",
    "productImageId": "b67b75ef1a7d872086"
  }
}
###     edit | amdin role | chỉnh sửa
PUT  http://localhost:8080/api/v1/product-image
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "productId": "10e32bc189f5959a39",
    "name": "value test 456111",
    "main": true,
    "image": "f88",
    "productImageId": "b67b75ef1a7d872086"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "productImageId": "b67b75ef1a7d872086",
    "productId": "10e32bc189f5959a39",
    "name": "value test 456111",
    "main": true,
    "image": "f88",
    "product_id": "10e32bc189f5959a39"
  }
}
###     delete | admin role | xóa hình ảnh
DELETE  http://localhost:8080/api/v1/product-image/b67b75ef1a7d872086
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done"
}




### user ------------------------------------------------------------------------------------------
###     get
GET http://localhost:8080/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "userId": "43fec0ef558c1ad0bb",
    "firstName": "Hậu",
    "lastName": "Lê Trung",
    "role": "admin",
    "email": "leehaau@gmail.com",
    "birthDate": null,
    "gender": "nam",
    "createdAt": "2023-07-23T17:09:22.000Z",
    "modifiedAt": "2023-07-23T18:08:01.000Z",
    "verified": null
  }
}
###     update
PUT http://localhost:8080/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "firstName": "Hậu",
    "lastName": "Lê Trung",
    "email": "letruuuuunghau@gmail.com",
    "gender": "nam"
}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "userId": "43fec0ef558c1ad0bb",
    "firstName": "Hậu",
    "lastName": "Lê Trung",
    "role": "admin",
    "email": "letruuuuunghau@gmail.com",
    "birthDate": null,
    "gender": "nam",
    "createdAt": "2023-07-23T17:09:22.000Z",
    "modifiedAt": "2023-07-27T19:30:53.000Z",
    "verified": null
  }
}
###     get         role admin
GET http://localhost:8080/api/v1/user/ad6bddf402f8298c0e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "userId": "ad6bddf402f8298c0e",
    "firstName": "hau",
    "lastName": "leung",
    "role": "user",
    "email": "letrunghau@gmail.com",
    "birthDate": null,
    "gender": "nam",
    "createdAt": "2023-07-26T19:11:07.000Z",
    "modifiedAt": "2023-07-26T19:35:03.000Z",
    "verified": "2023-07-26T19:35:03.000Z"
  }
}
###     get all     role admin
GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": [
    {
      "userId": "43fec0ef558c1ad0bb",
      "firstName": "Hậu",
      "lastName": "Lê Trung",
      "role": "admin",
      "email": "leehaau@gmail.com",
      "birthDate": null,
      "gender": "nam",
      "createdAt": "2023-07-23T17:09:22.000Z",
      "modifiedAt": "2023-07-23T18:08:01.000Z",
      "verified": null
    },
    {
      "userId": "ad6bddf402f8298c0e",
      "firstName": "hau",
      "lastName": "leung",
      "role": "user",
      "email": "letrunghau@gmail.com",
      "birthDate": null,
      "gender": "nam",
      "createdAt": "2023-07-26T19:11:07.000Z",
      "modifiedAt": "2023-07-26T19:35:03.000Z",
      "verified": "2023-07-26T19:35:03.000Z"
    }
  ]
}
###     create         role admin
POST http://localhost:8080/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "firstName": "cv",
    "lastName": "cd",
    "role": "admin",
    "email": "lee@gmail.com",
    "gender": "nam"
}
### OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "firstName": "cv",
    "lastName": "cd",
    "role": "admin",
    "email": "lee@gmail.com",
    "gender": "nam",
    "userId": "80f507e628ba210503",
    "verified": null,
    "createdAt": "2023-07-27T19:24:58.067Z",
    "modifiedAt": "2023-07-27T19:24:58.067Z"
  }
}
###     edit        role admin
PUT http://localhost:8080/api/v1/admin/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A

{
    "userId":"80f507e628ba210503",
    "firstName": "c4447v",
    "lastName": "cd",
    "email": "leehaaau@gmail.com",
    "gender": "nam",
    "role":null,
    "birthDate":"2023-07-23T17:26:12.000Z"

}
###OUTPUT
{
  "status": 200,
  "message": "done",
  "data": {
    "userId": "80f507e628ba210503",
    "firstName": "c4447v",
    "lastName": "cd",
    "role": null,
    "email": "leehaaau@gmail.com",
    "birthDate": "2023-07-24",
    "gender": "nam",
    "createdAt": "2023-07-27T19:24:58.000Z",
    "modifiedAt": "2023-07-27T19:25:56.000Z",
    "verified": null
  }
}
###     delete  system role use
DELETE  http://localhost:8080/api/v1/user/80f507e628ba210503
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0M2ZlYzBlZjU1OGMxYWQwYmIiLCJpYXQiOjE2OTAxMzIxNjUsImV4cCI6MTY5MjcyNDE2NX0.rzBhDIL7JRNZQL7DplT-K5D7jvubz5PHrgLb9F9UM0A
###OUTPUT
{
  "status": 200,
  "message": "done"
}










