
### sig
GET http://localhost:8080/api
###     login
POST  http://localhost:8080/api/v1/sig/login
Content-Type: application/json

{
    "email":"leetrunghaau@gmail.com",
    "password":"gggg"
}
###     register
POST http://localhost:8080/api/v1/sig/register
Content-Type: application/json

{
    "firstName":"hau",
    "lastName":"leung",
    "email": "leetrunghaau@gmail.com",
    "password":"gggg"
}

###     email verification
###     logout
### account
###     get list by user     system role use for test
###     add     system role use for test
###     edit    system role use for test
###     get modifid at by user id
GET http://localhost:8080/api/v1/password-modified-at
###     change Password by user id
POST http://localhost:8080/api/v1/change-password
Content-Type: application/json
Authorization: myss eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5YWM5NWNjNjgxOTk5ZWQ1NWEiLCJyb2xlIjoidXNlciIsImlhdCI6MTY4OTAyMDQwNiwiZXhwIjoxNjkxNjEyNDA2fQ.VnPyBNl5q6S9hQMXucrZv_mcNaab4g4bY2myHr3-KTU

{
    "oldPassword":"jjuyt",
    "newPassword":"admin@123"
}
### address ------------------------------------------------------------------------------------------
###     getAddress | get address main in user id
GET http://localhost:8080/api/v1/address/get-one
Authorization: myss eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5YWM5NWNjNjgxOTk5ZWQ1NWEiLCJyb2xlIjoidXNlciIsImlhdCI6MTY4OTAyMDQwNiwiZXhwIjoxNjkxNjEyNDA2fQ.VnPyBNl5q6S9hQMXucrZv_mcNaab4g4bY2myHr3-KTU

###     getListAddress | get list address in user id
GET http://localhost:8080/api/v1/address/get-list
Authorization: myss eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5YWM5NWNjNjgxOTk5ZWQ1NWEiLCJyb2xlIjoidXNlciIsImlhdCI6MTY4OTAyMDQwNiwiZXhwIjoxNjkxNjEyNDA2fQ.VnPyBNl5q6S9hQMXucrZv_mcNaab4g4bY2myHr3-KTU

###     addAddress
POST  http://localhost:8080/api/v1/address/add
Content-Type: application/json

{
    "province":"hhh",
    "district": "nnnn",
    "commune":"hnhjhh",
    "detail":"jjjj",
    "phone": "gbghhh"
}

###     editAddress
###     deleteAddress
### bill ------------------------------------------------------------------------------------------
###     getListBill
###     getListBillByUserId
###     getBillByOrderId
### blog ------------------------------------------------------------------------------------------
###     getBlog
GET http://localhost:8080/api/v1/blog/66966a48b1b7aba63f
###     getAllBlog
GET http://localhost:8080/api/v1/blogs
###     getListBlogBycategoryId
###     addBlog
POST  http://localhost:8080/api/v1/blog
Content-Type: application/json

{
    "blogCategoryId":"af20a79d5cf8dec0ed",
    "title":"bài viết của đấng",
    "thumbnail":"éo có thumb",
    "introduction":"hello các bạn trẻ",
    "content":"clmm"
}
###     editBlog
PUT  http://localhost:8080/api/v1/blog
Content-Type: application/json

{
    "blogId": "66966a48b1b7aba63f",
    "blogCategoryId":"af20a79d5cf8dec0ed",
    "title":"bài viết của đấng 2",
    "thumbnail":"éo có thumb",
    "introduction":"hello các bạn trẻ",
    "content":"clmm"
}
###     deleteBlog
DELETE  http://localhost:8080/api/v1/blog/66966a48b1b7aba63f
### Blog Categories ------------------------------------------------------------------------------------------
###     get
GET http://localhost:8080/api/v1/blog-category/54
###     getAll
GET http://localhost:8080/api/v1/blog-categories
###     add
POST  http://localhost:8080/api/v1/blog-category
Content-Type: application/json

{
    "name":"blog tâm trạng",
    "parent":"kgggjhghjgjhg"
}
###     edit
PUT   http://localhost:8080/api/v1/blog-category
Content-Type: application/json

{
    "blogCategoryId": "b934911dbdab3543c0",
    "name":"blog tâm trạng 1",  
    "parent":"kgggjhghjgjhg"
}
###     delete
DELETE    http://localhost:8080/api/v1/blog-category/b1bb94d2e1e9293b75
### brand ------------------------------------------------------------------------------------------
###     get one
GET http://localhost:8080/api/v1/brand/54
###     getAll
GET http://localhost:8080/api/v1/brands
###     add
POST http://localhost:8080/api/v1/brand
Content-Type: application/json

{
      "name": "dddd",
      "description": "sdfsdzf",
      "blogLink": "dsfxcvzfd"
}
###     edit
PUT  http://localhost:8080/api/v1/brand
Content-Type: application/json

{
    "brandId": "c0f56594fa0a87a3c8",
      "name": "dien tu mobi",
      "description": "sdfsdzf",
      "blogLink": "dsfxcvzfd"
}
###     delete 
DELETE  http://localhost:8080/api/v1/brand/54
### cart ------------------------------------------------------------------------------------------
###     get cart
###     add product to cart
###     edit value product in cart 
###     delete product in cart 
### categories ------------------------------------------------------------------------------------------
###     get
GET  http://localhost:8080/api/v1/category/1335921e1ce62b7d65
###     getAll
GET  http://localhost:8080/api/v1/categories
###     add
POST   http://localhost:8080/api/v1/category
Content-Type: application/json  

{
    "name": "máy hàn",
    "parent": "null",
    "image":"jhgjhghghjgjhg"

}
###     edit
PUT http://localhost:8080/api/v1/category
Content-Type: application/json

{
    "categoryId": "b860cdae43a7fa35f5",
    "name": "máy hàn1",
    "parent": "null",
    "image":"jhgjhghghjgjhg"
}
###     delete
DELETE http://localhost:8080/api/v1/category/b860cdae43a7fa
### discount ------------------------------------------------------------------------------------------
###     get
GET http://localhost:8080/api/v1/discount/id
###     getAll
GET http://localhost:8080/api/v1/discounts
###     add
POST  http://localhost:8080/api/v1/discount
Content-Type: application/json

{
    "enableAt":"2023-07-17T21:09:59.000Z",
    "disableAt":"2024-07-17T21:09:59.000Z",
    "type":"cc",
    "value":50.000,
    "quantity":15,
    "code":"nhap code"
}

###     edit
PUT  http://localhost:8080/api/v1/discount
Content-Type: application/json

{
    "discountId": "8ef0c57e2305c805ea",
    "enableAt":"2023-07-17T21:09:59.000Z",
    "disableAt":"2026-07-17T21:09:59.000Z",
    "type":"cc",
    "value":176.8645,
    "quantity":15,
    "code":"nhap code"
}

###     delete  
DELETE http://localhost:8080/api/v1/discount/3cf69d60fb01b9c337

### distributor ------------------------------------------------------------------------------------------
###     getAll
###     add
###     edit
###     delete  
### importduct ------------------------------------------------------------------------------------------
###     getAll
###     add
###     edit
###     delete 
### notification ------------------------------------------------------------------------------------------
###     get
GET  http://localhost:8080/api/v1/notification/7aba53c611627dbf27
###     getAll
GET  http://localhost:8080/api/v1/notifications

###     add
POST  http://localhost:8080/api/v1/notification
Content-Type: application/json

{
    "name":"hello",
    "enableAt":"2023-07-17T09:30:54.000Z",
    "disableAt":"2023-08-17T09:30:54.000Z",
    "content":"motoj hangf daif lee thee"
}
###     edit
PUT   http://localhost:8080/api/v1/notification
Content-Type: application/json

{
    "notificationId": "7aba53c611627dbf27",
    "name":"hhhh",
    "enableAt":"2023-07-17T09:30:54.000Z",
    "disableAt":"2023-08-17T09:30:54.000Z",
    "content":"một ngày dài lê thê"
}
###     delete
DELETE    http://localhost:8080/api/v1/notification/6471e91f90e55ba531
### order ------------------------------------------------------------------------------------------
###     getAllByStatus
###     getListByUserId
###     add
###     edit
###     delete 
### order item ------------------------------------------------------------------------------------------
###     add all
###     edit
###     delete 
### product ------------------------------------------------------------------------------------------
###     get
GET http://localhost:8080/api/v1/product/1e48622b6f61216f82
###     getAll
GET http://localhost:8080/api/v1/products
###     add
POST  http://localhost:8080/api/v1/product
Content-Type: application/json

{
    "name": "dasas",
    "categoryId": "1335921e1ce62b7d65",
    "quantity": 9,
    "brandId": null,
    "information": "hjgfhj",
    "price": 79843,
    "status": "disable"
}

###     edit
PUT  http://localhost:8080/api/v1/product
Content-Type: application/json 

{
    "productId": "d5ebdefa5242e132e7",
      "name": "jhg",
      "categoryId": "1335921e1ce62b7d65",
      "quantity": 9,
      "brandId": "c0f56594fa0a87a3c8",
      "information": "hjgfhj",
      "price": 79843,
      "status": "enable",
      "brandId": "c0f56594fa0a87a3c8",
      "categoryId": "1335921e1ce62b7d65"
}
###     delete
DELETE http://localhost:8080/api/v1/product/d5ebdefa5242e132e7
### product detail ------------------------------------------------------------------------------------------
###     get
GET http://localhost:8080/api/v1/product-detail/5de015082f5d7d5ff7
###     get all
GET http://localhost:8080/api/v1/products-detail
###     get by product id
GET http://localhost:8080/api/v1/product-detail-product-id/hhhh

###     add
POST  http://localhost:8080/api/v1/product-detail
Content-Type: application/json

{
    "specifications":"hello",
    "productId":null,
    "description":"đây là sản phẩm không bán",
    "content":"my content",
    "location":"my location"
}
###     edit
PUT  http://localhost:8080/api/v1/product-detail
Content-Type: application/json

{
    "productDetailId":"5de015082f5d7d5ff7",
    "specifications":"1111",
    "productId":"10e32bc189f5959a39",
    "description":"đây là sản phẩm không bán",
    "content":"my content",
    "location":"my location"
}

###     delete
DELETE  http://localhost:8080/api/v1/product-detail/5de015082f5d7d5ff7

### product image ------------------------------------------------------------------------------------------
###     get
###     add
###     edit
###     delete
### user ------------------------------------------------------------------------------------------
###     get
GET http://localhost:8080/user/userId
###     get add
GET http://localhost:8080/users
###     add     system role use
POST http://localhost:8080/user
Content-Type: application/json

{

}
###     edit    user and admin role update info
PUT http://localhost:8080/user
Content-Type: application/json

{

}
###     edit    admin role update
PUT http://localhost:8080/update-role
Content-Type: application/json

{

}
###     delete  system role use
DELETE  http://localhost:8080/user/userId













